CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY UNIQUE,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_user_id ON users (id);

CREATE INDEX IF NOT EXISTS idx_email ON users (email);

CREATE TABLE IF NOT EXISTS apps (
    id INT PRIMARY KEY UNIQUE,
    name TEXT NOT NULL UNIQUE,
    secret TEXT NOT NULL UNIQUE
)